DROP TABLE SUPPORT_TICKETS;
CREATE TABLE SUPPORT_TICKETS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CUSTOMER_NAME TEXT NOT NULL,
	PRIORITY TEXT,
	ISSUE_SCORE INT
);

INSERT INTO SUPPORT_TICKETS(CUSTOMER_NAME, PRIORITY, ISSUE_SCORE)
VALUES('Dana', 'high', 95),
('Omar', 'medium', 74),
('Noa', 'high', 88);

SELECT *
FROM SUPPORT_TICKETS
WHERE PRIORITY = 'medium';

DELETE FROM SUPPORT_TICKETS
WHERE ID = 3;

INSERT INTO SUPPORT_TICKETS(CUSTOMER_NAME, PRIORITY, ISSUE_SCORE)
VALUES('Ohad', 'high', 93);

SELECT *
FROM SUPPORT_TICKETS;
